services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag-frontend
    depends_on:
      - api
    ports:
      - "8501:8501"